### PR TITLE
Refactor /me API endpoint + add localization

### PR DESCRIPTION
**Pull request by nschneble**
Refactors the `/me` endpoint to resolve the same bug that [malformed the Swagger docs](https://github.com/bullet-train-co/bullet_train-api/pull/7). Also adds localization.

### CODE REVIEW

**Comment by newstler** [comment]
Looks like this brakes the swagger docs at `/api/swagger.json`
I get:
```
NameError
uninitialized constant Api::V1::MeSerializer
Did you mean?
Api::V1::TeamSerializer
Extracted source (around line #280):
    # unknown.
    def constantize(camel_cased_word)
      Object.const_get(camel_cased_word)
    end

    # Tries to find a constant with the name specified in the argument string.

[Application Trace](https://bullettrainapi.eu.ngrok.io/api/docs/swagger#) | [Framework Trace](https://bullettrainapi.eu.ngrok.io/api/docs/swagger#) | [Full Trace](https://bullettrainapi.eu.ngrok.io/api/docs/swagger#)
[activesupport (7.0.2.3) lib/active_support/inflector/methods.rb:280:in `constantize' ](https://bullettrainapi.eu.ngrok.io/api/docs/swagger#)
[activesupport (7.0.2.3) lib/active_support/core_ext/string/inflections.rb:74:in `constantize' ](https://bullettrainapi.eu.ngrok.io/api/docs/swagger#)
[grape-swagger (1.4.2) lib/grape-swagger/endpoint.rb:373:in `expose_params_from_model' ](https://bullettrainapi.eu.ngrok.io/api/docs/swagger#)
[grape-swagger (1.4.2) lib/grape-swagger/endpoi](https://bullettrainapi.eu.ngrok.io/api/docs/swagger#)
...
```

**Comment by andrewculver** [comment]
Yeah, I didn't catch that issue when I merged this. I did run into issues with `config/locales/en/me.en.yml` because the whitespace was all messed up and the Yaml wouldn't parse. Honestly can't remember why I merged this before getting it working on the feature branch. Need to undo this.

**Comment by andrewculver** [comment]
We must not have a test around the `/api/v1/me` endpoint?

**Comment by andrewculver** [comment]
@nschneble The following line breaks `/api/v1/me`:

```
    desc Api.title(:show), &Api.show_desc
```

**Comment by andrewculver** [comment]
Fixed in https://github.com/bullet-train-co/bullet_train-api/commit/acacd5deb2d89b7f1e858aab2350f6c26ba7df6c and https://github.com/bullet-train-co/bullet_train-api/commit/3b464d56880bf877eba863b77464acc512a6018f .

**Pull request merged**
